# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find UCL
#'
#' Compute approximated pvalue for the Tb test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
find_UCL <- function(reference_sample, n, target_ARL, nsim, nperm, test) {
    .Call(`_turbostat_find_ucl_conditional`, reference_sample, n, target_ARL, nsim, nperm, test)
}

calibrate.uncoditional <- function(m, n, nsim, nperm, lcl_seq, test, run_length_cap) {
    .Call(`_turbostat_find_lcl_uncoditional`, m, n, nsim, nperm, lcl_seq, test, run_length_cap)
}

#' Test UCL
#'
#' Compute approximated pvalue for the Tb test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
rl.conditional <- function(reference_sample, n, nsim, nperm, shifts, LCL, test, run_length_cap) {
    .Call(`_turbostat_conditional_run_length_distribution_bootstrap`, reference_sample, n, nsim, nperm, shifts, LCL, test, run_length_cap)
}

#' Test UCL
#'
#' Compute approximated pvalue for the Tb test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
rl.uncoditional <- function(m, n, nsim, nperm, shifts, LCL, test, run_length_cap) {
    .Call(`_turbostat_unconditional_run_length_distribution`, m, n, nsim, nperm, shifts, LCL, test, run_length_cap)
}

#' Ta permutation test
#'
#' Compute approximated pvalue for the Ta test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
turbostat.setseed <- function(s) {
    invisible(.Call(`_turbostat_setseed`, s))
}

#' Ta permutation test
#'
#' Compute approximated pvalue for the Ta test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
permtest.ta <- function(x1, x2, B) {
    .Call(`_turbostat_t_a_binding`, x1, x2, B)
}

#' Tb permutation test
#'
#' Compute approximated pvalue for the Tb test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
permtest.tb <- function(x1, x2, B) {
    .Call(`_turbostat_t_b_binding`, x1, x2, B)
}

#' Tc permutation test
#'
#' Compute approximated pvalue for the Tc test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
permtest.tc <- function(x1, x2, B) {
    .Call(`_turbostat_t_c_binding`, x1, x2, B)
}

#' Tabc permutation test
#'
#' Compute approximated pvalue for the Tabc test using a finite number of permutations.
#'
#' @param x1 An numeric vector
#' @param x2 An numeric vector
#' @param B the number of permutations to be used for estimating the pvalue
#' @export
permtest.tabc <- function(x1, x2, B) {
    .Call(`_turbostat_t_abc_binding`, x1, x2, B)
}

