# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello <- function() {
    .Call(`_turbostat_hello`)
}

bigSum <- function(x) {
    .Call(`_turbostat_bigSum`, x)
}

sumOfRanks <- function(sample_R) {
    .Call(`_turbostat_sumOfRanks`, sample_R)
}

