# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Phase II monitoring
#'
#' Compute the observed value of the monitoring statistic
#'
#' @param x1 The reference sample
#' @param x2 The test sample
#' @param monitoring_statistic_type Either "npc" or "simple_statistic"
#' @param monitoring_statistic_parameters A list with type-specific parameters of the monitoring statistic. For the
#' "simple_statistic" type the only parameter is "statistic" which should be set to a valid statistic key.
#' For the "npc" type the four (required) parameters are "statistics", "permutation_distributions", "tails" and
#' "combining_function". The "statistics", "permutation_distributions" and "tails" parameters should be three lists of the
#' same length. The "combining_function" parameters should be a string. See details for consulting the available statistics and combining
#' functions and the keys to be used.
#' @returns the monitoring statistic value
#' @details
#' The supported statistics and the respective keys to be used are:
#' \itemize{
#'  \item{Wilcoxon rank sum - "wilcoxon_rank_sum"}
#'  \item{Mann-Whitney - "mann_whitney"}
#'  \item{Mean-normalized wilcoxon rank sum  - "centered_wilcoxon_rank_sum"}
#'  \item{ Percentile modified rank test with s=r=0.42 - "percentiles_42_42"}
#'  \item{ Percentile modified rank test with s=r=0.46 - "percentiles_46_46"}
#'  \item{Klotz - "klotz_statistic"}
#'  \item{Ansari Bradely - "ab_statistic"}
#'  \item{Lepage - "lepage"}
#'  \item{Cucconi - "cucconi"}
#' }
#' The three options for the values of the "tails" list parameter of npc monitoring statistics are: "two_sided", "left" and "right"
#' The three options for the "combining_function" parameter of npc monitoring statistics are: "fisher", "liptak" and "tippet"
#' @export
compute_monitoring_statistic <- function(x1, x2, monitoring_statistic_type, monitoring_statistic_parameters) {
    .Call(`_npcharts_compute_monitoring_statistic`, x1, x2, monitoring_statistic_type, monitoring_statistic_parameters)
}

#' Unconditional calibration
#'
#' Unconditional calibration for the Stehwart-type charts implemented by this package
#'
#' @param m The dimension used for the reference sample
#' @param n The dimension used for the test samples
#' @param distribution_key A string which identifies a distribution or a distribution family. Used in combination
#' with the "distribution_parameters" parameter in order to select the IC distribution. See details for consulting
#' the available distributions and the respective keys.
#' @param distribution_parameters A list with the distribution parameters (an empty list should be supplied if the distribution has not parameters)
#' @param monitoring_statistic_type Either "npc" or "simple_statistic"
#' @param monitoring_statistic_parameters A list with type-specific parameters of the monitoring statistic. For the
#' "simple_statistic" type the only parameter is "statistic" which should be set to a valid statistic key.
#' For the "npc" type the four (required) parameters are "statistics", "permutation_distributions", "tails" and
#' "combining_function". The "statistics", "permutation_distributions" and "tails" parameters should be three lists of the
#' same length. The "combining_function" parameters should be a string. See details for consulting the available statistics and combining
#' functions and the keys to be used.
#' @param limits_seq The numeric vector of limits for which the run length should be recorded at each simulation
#' @param is_upper_limit A boolean parameter used to select whether the chart uses an upper limit or a lower limit
#' @param nsim The number of simulations
#' @param run_length_cap A limit for the run length in the simulations used to guarantee convergence of the algorithm
#' @return A numeric matrix of size nsim x length(limits_seq)
#' @details The supported distributions and the respective parameters are:
#' \itemize{
#'  \item{Normal - key:"norm", params:"mean" and "sd"}
#'  \item{Laplace - key:"laplace", params:"location" and "scale"}
#'  \item{Student's T - key:"t", params:"df"}
#'  \item{Cauchy - key:"laplace", params:"location" and "scale"}
#'  \item{Chi squared - key:"chi_squared", params:"df"}
#'  \item{Exp(lambda=1) shifted by -1 - key:"normalized_rate_one_exponential"}
#'  \item{Gamma(scale=4,shape=2) shifted by -2 - key:"centered_gamma_with_shape_equal_four"}
#' }
#' The supported statistics and the respective keys to be used are:
#' \itemize{
#'  \item{Wilcoxon rank sum - "wilcoxon_rank_sum"}
#'  \item{Mann-Whitney - "mann_whitney"}
#'  \item{Mean-normalized wilcoxon rank sum  - "centered_wilcoxon_rank_sum"}
#'  \item{ Percentile modified rank test with s=r=0.42 - "percentiles_42_42"}
#'  \item{ Percentile modified rank test with s=r=0.46 - "percentiles_46_46"}
#'  \item{Klotz - "klotz_statistic"}
#'  \item{Ansari Bradely - "ab_statistic"}
#'  \item{Lepage - "lepage"}
#'  \item{Cucconi - "cucconi"}
#' }
#' The three options for the values of the "tails" list parameter of npc monitoring statistics are: "two_sided", "left" and "right".
#' The three options for the "combining_function" parameter of npc monitoring statistics are: "fisher", "liptak" and "tippet"
#' @export
calibrate.unconditional <- function(m, n, distribution_key, distribution_parameters, monitoring_statistic_type, monitoring_statistic_parameters, limits_seq, is_upper_limit, nsim, run_length_cap) {
    .Call(`_npcharts_calibrate_unconditional`, m, n, distribution_key, distribution_parameters, monitoring_statistic_type, monitoring_statistic_parameters, limits_seq, is_upper_limit, nsim, run_length_cap)
}

#' Unconditional evaluation
#'
#' Unconditional evaluation for Stehwart-type charts
#'
#' @param m The dimension used for the reference sample
#' @param n The dimension used for the test samples
#' @param distribution_key A string which identifies a distribution or a distribution family. Used in combination
#' with the "distribution_parameters" parameter in order to select the IC distribution. See details for consulting
#' the available distributions and the respective keys.
#' @param distribution_parameters A list with the distribution parameters (an empty list should be supplied if the distribution has not parameters)
#' @param monitoring_statistic_type Either "npc" or "simple_statistic"
#' @param monitoring_statistic_parameters A list with type-specific parameters of the monitoring statistic. For the
#' "simple_statistic" type the only parameter is "statistic" which should be set to a valid statistic key.
#' For the "npc" type the four (required) parameters are "statistics", "permutation_distributions", "tails" and
#' "combining_function". The "statistics", "permutation_distributions" and "tails" parameters should be three lists of the
#' same length. The "combining_function" parameters should be a string. See details for consulting the available statistics and combining
#' functions and the keys to be used.
#' the only parameter is "statistic" which should be set to a valid statistic key. For the "npc" type the three
#' (required) parameters are "statistics", "permutation_distributions" and "tails"
#' @param nsim The number of simulations
#' @param run_length_cap A limit for the run length in the simulations used to guarantee convergence of the algorithm
#' @returns A data frame whose columns are "run_lengths", "reference_sample_means" and "reference_sample_sds"
#' @details The supported distributions and the respective parameters are:
#' \itemize{
#'  \item{Normal - key:"norm", params:"mean" and "sd"}
#'  \item{Laplace - key:"laplace", params:"location" and "scale"}
#'  \item{Student's T - key:"t", params:"df"}
#'  \item{Cauchy - key:"laplace", params:"location" and "scale"}
#'  \item{Chi squared - key:"chi_squared", params:"df"}
#'  \item{Exp(lambda=1) shifted by -1 - key:"normalized_rate_one_exponential"}
#'  \item{Gamma(scale=4,shape=2) shifted by -2 - key:"centered_gamma_with_shape_equal_four"}
#' }
#' The supported statistics and the respective keys to be used are:
#' \itemize{
#'  \item{Wilcoxon rank sum - "wilcoxon_rank_sum"}
#'  \item{Mann-Whitney - "mann_whitney"}
#'  \item{Mean-normalized wilcoxon rank sum  - "centered_wilcoxon_rank_sum"}
#'  \item{ Percentile modified rank test with s=r=0.42 - "percentiles_42_42"}
#'  \item{ Percentile modified rank test with s=r=0.46 - "percentiles_46_46"}
#'  \item{Klotz - "klotz_statistic"}
#'  \item{Ansari Bradely - "ab_statistic"}
#'  \item{Lepage - "lepage"}
#'  \item{Cucconi - "cucconi"}
#' }
#' The three options for the values of the "tails" list parameter of npc monitoring statistics are: "two_sided", "left" and "right".
#' The three options for the "combining_function" parameter of npc monitoring statistics are: "fisher", "liptak" and "tippet"
#' @export
evaluate.unconditional <- function(m, n, limits, location_shift, scale_multiplier, distribution_key, distribution_parameters, monitoring_statistic_type, monitoring_statistic_parameters, nsim, run_length_cap) {
    .Call(`_npcharts_evaluate_unconditional`, m, n, limits, location_shift, scale_multiplier, distribution_key, distribution_parameters, monitoring_statistic_type, monitoring_statistic_parameters, nsim, run_length_cap)
}

calibrate.conditional <- function(reference_sample, n, monitoring_statistic_key, monitoring_statistic_parameters, target_ARL, is_upper_limit, nsim) {
    .Call(`_npcharts_calibrate_conditional`, reference_sample, n, monitoring_statistic_key, monitoring_statistic_parameters, target_ARL, is_upper_limit, nsim)
}

evaluate.conditional <- function(reference_sample, n, limit, is_upper_limit, shifts, monitoring_statistic_key, monitoring_statistic_parameters, nsim, run_length_cap) {
    .Call(`_npcharts_evaluate_conditional`, reference_sample, n, limit, is_upper_limit, shifts, monitoring_statistic_key, monitoring_statistic_parameters, nsim, run_length_cap)
}

#' Compute permutation distribution
#'
#' Used for precomputing permutation distribution of linear rank statistics
#'
#' @param m The dimension used for the reference sample
#' @param n The dimension used for the test samples
#' @param statistic should be set to a valid statistic key. See details for consulting the available statistics
#' and corresponding keys
#' @param nperm the number of random permutations
#' @details
#' The supported statistics and the respective keys to be used are:
#' \itemize{
#'  \item{Wilcoxon rank sum - "wilcoxon_rank_sum"}
#'  \item{Mann-Whitney - "mann_whitney"}
#'  \item{Mean-normalized wilcoxon rank sum  - "centered_wilcoxon_rank_sum"}
#'  \item{ Percentile modified rank test with s=r=0.42 - "percentiles_42_42"}
#'  \item{ Percentile modified rank test with s=r=0.46 - "percentiles_46_46"}
#'  \item{Klotz - "klotz_statistic"}
#'  \item{Ansari Bradely - "ab_statistic"}
#'  \item{Lepage - "lepage"}
#'  \item{Cucconi - "cucconi"}
#' }
#' @export
compute_permutation_distribution <- function(statistic, m, n, n_perm) {
    .Call(`_npcharts_compute_permutation_distribution_r`, statistic, m, n, n_perm)
}

#' Set the seed used by this R packet
#'
#' @param seed The seed. Either an integer scalar or an integer vector of length 2 representing a 64-bit seed.
#' @export
npcharts.setseed <- function(seed) {
    invisible(.Call(`_npcharts_set_seed`, seed))
}

#' Ta permutation test
#'
#' Estimate the right tail permutation pvalue for the Ta test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.ta <- function(x1, x2, B) {
    .Call(`_npcharts_t_a_binding`, x1, x2, B)
}

#' Tb permutation test
#'
#' Estimate the right tail permutation pvalue for the Tb test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.tb <- function(x1, x2, B) {
    .Call(`_npcharts_t_b_binding`, x1, x2, B)
}

#' Tc permutation test
#'
#' Estimate the right tail permutation pvalue for the Tc test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.tc <- function(x1, x2, B) {
    .Call(`_npcharts_t_c_binding`, x1, x2, B)
}

#' Tabc combined permutation test
#'
#' Estimate the right tail permutation pvalue for the Tabc test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.tabc <- function(x1, x2, B) {
    .Call(`_npcharts_t_abc_binding`, x1, x2, B)
}

#' Tab combined permutation test
#'
#' Estimate the right tail permutation pvalue for the Tab test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.tab <- function(x1, x2, B) {
    .Call(`_npcharts_t_ab_binding`, x1, x2, B)
}

#' Tbc combined permutation test
#'
#' Estimate the right tail permutation pvalue for the Tbc test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.tbc <- function(x1, x2, B) {
    .Call(`_npcharts_t_bc_binding`, x1, x2, B)
}

#' Tac combined permutation test
#'
#' Estimate the right tail permutation pvalue for the Tac test using a finite number of permutations.
#'
#' @param x1 The first group's observations provided as a numeric vector.
#' @param x2 The second group's observations provided as a numeric vector.
#' @param B The number of permutations used for estimating the pvalue
#' @return The estimated permutation pvalue and the observed statistic
#' @export
permtest.tac <- function(x1, x2, B) {
    .Call(`_npcharts_t_ac_binding`, x1, x2, B)
}

#' @export
test.gamma <- function(n) {
    .Call(`_npcharts_centered_gamma_with_shape_equal_four_r_test`, n)
}

#' @export
test.gamma2 <- function(n) {
    .Call(`_npcharts_mirrored_centered_gamma_with_shape_equal_four_r_test`, n)
}

test.exp <- function(n) {
    .Call(`_npcharts_test_exp`, n)
}

#' @export
test.t_due_e_mezzo <- function(n) {
    .Call(`_npcharts_test_t_due_e_mezzo`, n)
}

test.laplace <- function(n, location, scale) {
    .Call(`_npcharts_test_laplace`, n, location, scale)
}

test.cauchy <- function(n, location, scale) {
    .Call(`_npcharts_test_cauchy`, n, location, scale)
}

test.standard_half_cauchy <- function(n) {
    .Call(`_npcharts_test_standard_half_cauchy`, n)
}

test1 <- function(n) {
    .Call(`_npcharts_test1`, n)
}

test.ansari_bradley <- function(x1, x2) {
    .Call(`_npcharts_test_ansari_bradley`, x1, x2)
}

test.difference_of_means_klotz <- function(x1, x2) {
    .Call(`_npcharts_test_difference_of_means_klotz`, x1, x2)
}

test.lepage <- function(x1, x2) {
    .Call(`_npcharts_test_lepage`, x1, x2)
}

test.cucconi <- function(x1, x2) {
    .Call(`_npcharts_test_cucconi`, x1, x2)
}

#' @export
test.percentiles <- function(x1, x2, r, s) {
    .Call(`_npcharts_test_percentiles`, x1, x2, r, s)
}

#' @export
test.centered_percentiles <- function(x1, x2, r, s) {
    .Call(`_npcharts_test_centered_percentiles`, x1, x2, r, s)
}

hello <- function() {
    .Call(`_npcharts_hello`)
}

