# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hello <- function() {
    .Call(`_cucconi_hello`)
}

bigSum <- function(x) {
    .Call(`_cucconi_bigSum`, x)
}

multisampleCucconiTest <- function(samples, B) {
    .Call(`_cucconi_multisampleCucconiTest`, samples, B)
}

